services:
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:14.8-alpine3.18
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    env_file:
      - ./.env

  app:
    container_name: crm
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./crm/uploads:/app/crm/uploads
    depends_on:
      - postgres
      - redis
    restart: on-failure
    command: sh -c "
      python ./manage.py migrate &&
      python ./manage.py create_entities &&
      python ./manage.py runserver 0.0.0.0:8000
      "

  celery:
    build: .
    depends_on:
      - redis
      - app
    command: celery -A crm worker -B -l info




