# Generated by Django 5.1.2 on 2024-11-06 13:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Стоимость",
            ),
        ),
    ]
