# Generated by Django 5.1.2 on 2024-11-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_delete_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Стоимость"
            ),
            preserve_default=False,
        ),
    ]
