# Generated by Django 5.1.2 on 2024-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_end_date"),
        ("customers", "0002_remove_customer_lead_contract_unique_and_more"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customer",
            name="lead_contract_unique",
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("lead_id", "contract_id"),
                name="lead_contract_unique",
                violation_error_message="Клиент уже подписал этот контракт",
            ),
        ),
    ]
