# Generated by Django 5.1.2 on 2024-11-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_end_date"),
        ("customers", "0003_remove_customer_lead_contract_unique_and_more"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.contract",
                verbose_name="Контракт",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.lead",
                verbose_name="Клиент",
            ),
        ),
    ]
