# Generated by Django 5.1.2 on 2024-11-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_customer_contract_alter_customer_lead"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "verbose_name": "Активный клиент",
                "verbose_name_plural": "Активные клиенты",
            },
        ),
    ]
