# Generated by Django 5.1.2 on 2024-11-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ads_budget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ads",
            options={"verbose_name": "Реклама", "verbose_name_plural": "Рекламы"},
        ),
    ]
