# Generated by Django 5.1.2 on 2024-11-05 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0002_alter_ads_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=64, verbose_name="Фамилия")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть в формате: '+999999999'. Не больше 15 цифр.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                ("email", models.EmailField(max_length=64, verbose_name="Почта")),
                (
                    "ad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="ads.ads",
                        verbose_name="Рекламная компания",
                    ),
                ),
            ],
        ),
    ]
