# Generated by Django 5.1.2 on 2024-11-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"verbose_name": "Клиенты", "verbose_name_plural": "Клиенты"},
        ),
    ]
