# Generated by Django 5.1.2 on 2024-11-05 12:47

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_uuid_alter_contract_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateTimeField(
                validators=[contracts.models.validate_end_date],
                verbose_name="Действует до",
            ),
        ),
    ]
