# Generated by Django 5.1.2 on 2024-11-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"verbose_name": "Контракт", "verbose_name_plural": "Контракты"},
        ),
        migrations.AddField(
            model_name="contract",
            name="archived",
            field=models.BooleanField(
                choices=[(0, "Действителен"), (1, "Срок действия истёк")], default=1
            ),
        ),
    ]
