# Generated by Django 5.1.2 on 2024-11-06 14:09

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_alter_contract_options_contract_archived"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contract",
            managers=[
                ("unarchived", django.db.models.manager.Manager()),
            ],
        ),
    ]
