# Generated by Django 5.1.2 on 2024-11-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_contract_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="archived",
            field=models.BooleanField(
                choices=[(1, "Срок действия истёк"), (0, "Действителен")], default=0
            ),
        ),
    ]
