# Generated by Django 5.1.2 on 2024-11-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_alter_contract_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="archived",
            field=models.BooleanField(
                choices=[(1, "Недействителен"), (0, "Действителен")],
                default=0,
                verbose_name="Срок действия",
            ),
        ),
    ]
