# Generated by Django 5.1.2 on 2024-11-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_remove_contract_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="archived",
            field=models.BooleanField(
                choices=[(True, "Недействителен"), (False, "Действителен")],
                default=0,
                verbose_name="Срок действия",
            ),
        ),
    ]
