# Generated by Django 5.1.2 on 2024-11-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_contract_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Истек"),
        ),
    ]
